In [1]:
import utils as ut
import sys
import numpy as np
import pandas as pd

sys.path.insert(0, '../')
from data.process_data import get_adult_data, get_compas_data

In [2]:
DATASET ={
	'Adult':{
		'folder': '../data/adult',
		'SENSITIVE_ATTRS': ['gender_Female', 'gender_Male'],
		'INDICATOR': 'gender_Male',
		'func': get_adult_data,
		'sample': 10000
    },
	'COMPAS':{
		'folder': '../data/compas',
		'SENSITIVE_ATTRS': ['race_African-American', 'race_Caucasian'],
		'INDICATOR': 'race_Caucasian',
		'func': get_compas_data,
		'sample': 2000
    }
}

In [3]:
data_name = 'Adult'
profile = DATASET[data_name]

### load data
train_df, test_df, feature_names, label_name = profile['func'](profile['folder'])

SENSITIVE_ATTRS = profile['SENSITIVE_ATTRS']
INDICATOR = profile['INDICATOR']
	
### prepare for the modeling
# split x, y, and the sensitive attrs
# prepare x for the linear classifier
# convert y into {-1, 1}
x_train, y_train, x_control_train, x_test, y_test, x_control_test = ut.process_train_test_df(train_df, test_df, label_name,
																							   SENSITIVE_ATTRS, [INDICATOR],
																								intercept=True, as_negative=True)

In [4]:
train_df.columns

Index(['label', 'workclass_?', 'workclass_Federal-gov', 'workclass_Local-gov',
       'workclass_Never-worked', 'workclass_Private', 'workclass_Self-emp-inc',
       'workclass_Self-emp-not-inc', 'workclass_State-gov',
       'workclass_Without-pay',
       ...
       'capital_loss_3', 'hours_per_week_0', 'hours_per_week_1',
       'hours_per_week_2', 'hours_per_week_3', 'education_num_0',
       'education_num_1', 'education_num_2', 'education_num_3',
       'native_country_Holand-Netherlands'],
      dtype='object', length=123)

In [5]:
len(feature_names)

122

In [6]:
x_train.shape

(32561, 121)

In [7]:
y_train[0:10]

array([-1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.])

In [8]:
x_control_train.keys()

dict_keys(['gender_Male'])

In [10]:
x_control_train[INDICATOR][0:10]

array([1., 1., 1., 1., 0., 0., 0., 1., 0., 1.])

In [12]:
data_name = 'COMPAS'
profile = DATASET[data_name]

### load data
train_df, test_df, feature_names, label_name = profile['func'](profile['folder'])

SENSITIVE_ATTRS = profile['SENSITIVE_ATTRS']
INDICATOR = profile['INDICATOR']
	
### prepare for the modeling
# split x, y, and the sensitive attrs
# prepare x for the linear classifier
# convert y into {-1, 1}
x_train, y_train, x_control_train, x_test, y_test, x_control_test = ut.process_train_test_df(train_df, test_df, label_name,
																							   SENSITIVE_ATTRS, [INDICATOR],
																								intercept=True, as_negative=True)

In [13]:
train_df.columns

Index(['days_b_screening_arrest', 'c_charge_degree_F', 'c_charge_degree_M',
       'race_African-American', 'race_Caucasian', 'score_text_High',
       'score_text_Low', 'score_text_Medium', 'sex_Female', 'sex_Male',
       'age_0', 'age_1', 'age_2', 'age_3', 'age_4', 'age_5', 'decile_score_0',
       'decile_score_1', 'decile_score_2', 'decile_score_3', 'decile_score_4',
       'decile_score_5', 'priors_count_0.0', 'priors_count_1.0',
       'priors_count_2.0', 'priors_count_3.0', 'priors_count_4.0',
       'two_year_norecid'],
      dtype='object')

In [14]:
len(feature_names)

27

In [15]:
x_train.shape

(3483, 26)

In [16]:
x_control_train.keys()

dict_keys(['race_Caucasian'])

In [17]:
x_control_train[INDICATOR][0:10]

array([0., 1., 0., 0., 0., 0., 0., 1., 0., 0.])